version:  '3.8'

phases:
  pre_build:
    commands
      - echo "Initializing Terraform..."
      - terraform init
      - terraform validate
  build:
    commands:
      - echo "Running Terraform Test Framework..."
      - terraform test